export const TEXT = "The origins of the Internet date back to the of packet switching and research commissioned by the United States Department of Defense in the toenable time sharing of computers The primary precursor network the ARPANET initially served as a backbone for interconnection of regional academic and military networks in the  The funding of the National Science Foundation Network as a new backbone in the as well as private funding for other commercial extensions led to worldwide participation in the development of new networking technologies and the merger of many networks The linking of commercial networks and enterprises by the early marked the beginning of the transition to the modern Internet and generated a sustained exponential growth as generations of institutional personal and mobile computers were connected to the network Although the Internet  was widely used by academia in the commercialization incorporated its services and technologies into virtually every aspect of modern life".toLowerCase()


const TEXTS = [
    "Computer programming is the process of performing a particular computation or more generally accomplishing a specific computing result usually by designing and building an executable computer program Programming involves tasks such as analysis generating algorithms profiling algorithms accuracy and resource consumption and the implementation of algorithms usually in a chosen programming language commonly referred to as coding The source code of a program is written in one or more languages that are intelligible to programmers rather than machine code which is directly executed by the central processing unit The purpose of programming is to find a sequence of instructions that will automate the performance of a task which can be as complex as an operating system on a computer often for solving a given problem Proficient programming thus usually requires expertise in several different subjects including knowledge of the application domain specialized algorithms and formal logic",
    "Tasks accompanying and related to programming include testing debugging source code maintenance implementation of build systems and management of derived artifacts such as the machine code of computer programs These might be considered part of the programming process but often the term software development is used for this larger process with the term programming implementation or coding reserved for the actual writing of code Software engineering combines engineering techniques with software development practices Reverse engineering is a related process used by designers analysts and programmers to understand and re-create or re-implement",
    "High level languages made the process of developing a program simpler and more understandable and less bound to the underlying hardware The first compiler related tool the A System was developed in by Grace Hopper who also coined the term compiler FORTRAN the first widely used high level language to have a functional implementation came out in and many other languages were soon developed in particular COBOL aimed at commercial data processing and Lisp for computer research These compiled languages allow the programmer to write programs in terms that are syntactically richer and more capable of abstracting the code making it easy to target for varying machine instruction sets via compilation declarations and heuristics Compilers harnessed the power of computers to make programming easier by allowing programmers to specify calculations by entering a formula using infix notation",
    "The origins of the Internet date back to the of packet switching and research commissioned by the United States Department of Defense in the toenable time sharing of computers The primary precursor network the ARPANET initially served as a backbone for interconnection of regional academic and military networks in the  The funding of the National Science Foundation Network as a new backbone in the as well as private funding for other commercial extensions led to worldwide participation in the development of new networking technologies and the merger of many networks The linking of commercial networks and enterprises by the early marked the beginning of the transition to the modern Internet and generated a sustained exponential growth as generations of institutional personal and mobile computers were connected to the network Although the Internet  was widely used by academia in the commercialization incorporated its services and technologies into virtually every aspect of modern life",
    "Machine code was the language of early programs written in the instruction set of the particular machine often in binary notation Assembly languages were soon developed that let the programmer specify instruction in a text format ADD X TOTAL with abbreviations for each operation code and meaningful names for specifying addresses However because an assembly language is little more than a different notation for a machine language two machines with different instruction sets also have different assembly languages",
    "Debugging is a very important task in the software development process since having defects in a program can have significant consequences for its users Some languages are more prone to some kinds of faults because their specification does not require compilers to perform as much checking as other languages Use of a static code analysis tool can help detect some possible problems Normally the first step in debugging is to attempt to reproduce the problem. This can be a non-trivial task for example as with parallel processes or some unusual software bugs Also specific user environment and usage history can make it difficult to reproduce the problem",
    "After the bug is reproduced the input of the program may need to be simplified to make it easier to debug For example when a bug in a compiler can make it crash when parsing some large source file a simplification of the test case that results in only few lines from the original source file can be sufficient to reproduce the same crash Tria and error divide and conquer is needed the programmer will try to remove some parts of the original test case and check if the problem still exists When debugging the problem in a GUI the programmer can try to skip some user interaction from the original problem description and check if remaining actions are sufficient for bugs to appear Scripting and breakpointing is also part of this process",
    "Individuals differ from one another in their ability to understand complex ideas to adapt effectively to the environment to learn from experience to engage in various forms of reasoning to overcome obstacles by taking thought Although these individual differences can be substantial they are never entirely consistent a given persons intellectual performance will vary on different occasions in different domains as judged by different criteria Concepts of intelligence are attempts to clarify and organize this complex set of phenomena Although considerable clarity has been achieved in some areas no such conceptualization has yet answered all the important questions and none commands universal assent Indeed when two dozen prominent theorists were recently asked to define intelligence they gave two dozen somewhat different definitions",
    "Scholars studying artificial intelligence have proposed definitions of intelligence that include the intelligence demonstrated by machines Some of these definitions are meant to be general enough to encompass human and other animal intelligence as well An intelligent agent can be defined as a system that perceives its environment and takes actions which maximize its chances of success.[35] Kaplan and Haenlein define artificial intelligence as  systems ability to correctly interpret external data to learn from such data and to use those learnings to achieve specific goals and tasks through flexible adaptation Progress in artificial intelligence can be demonstrated in benchmarks ranging from games to practical tasks such as protein folding Existing AI lags humans in terms of general intelligence which is sometimes defined as the capacity to learn how to carry out a huge range of tasks",
    "Marions sister Lila arrives in Fairvale a week later tells Sam about the theft and demands to know her whereabouts He denies knowing anything about her disappearance A private investigator named Arbogast approaches them saying that he has been hired to retrieve the money Arbogast stops at the Bates Motel and questions Norman whose nervous behavior and inconsistent answers arouse his suspicion He examines the guest register and discovers from her handwriting that Marion spent a night at the motel When Arbogast learns that Marion had spoken to Normans mother Arbogast asks to speak to her but Norman refuses to allow it Arbogast updates Sam and Lila about his search and promises to phone again in an hour After he enters the Bates home to search for Normans mother a shadowy figure in a dress emerges from the bedroom and stabs him to death"
]

export function GetText(){
    const textIndex = Math.random().toString().substring(2,3)
    return TEXTS[textIndex].toLowerCase().trim()
}